name: Build

on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check codestyle
        run: clang-format src/app/app.c src/libapp/definitions.c src/libapp/definitions.h src/libapp/interface.c src/libapp/interface.h src/libapp/parser.c src/libapp/parser.h -i --verbose
        
      - name: Build application
        run: make
        
      - name: Build tests
        run: make test