name: Build

on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check codestyle
        run: clang-format src/app/app.c src/libapp/randtext.c -i --verbose
        git diff --exit-code

      - name: Build application
        run: make