name: Build

on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check codestyle
        run: $files=(git ls-files); foreach ($file in $files) { if ((get-item $file).Extension -in ".c", ".h") { &clang-format -i --verbose $file } }
        
      - name: Build application
        run: make
        
      - name: Build tests
        run: make test